### ISSUE TITLE
replaying a built-in returned a different result than expected - part 2

### ISSUE THREAD

**Issue by Cloven** [parapluu/Concuerror#74]
Hi guys --

I have another repeatable one of these using current parapluu/Concuerror master (01f0592a39b8f6ad3b0b93febe9aff807b496de6).

You still have read access to the repo which triggers this, which is Cloven/paros.  The specific commit that I ran this with was 31bf74bc315d5ff52cbb336c883210ac287c6bb7, which is as of this writing currently master's head commit.

the command I used to invoke:

../Concuerror/concuerror --pa ebin --pa deps/goldrush/ebin --pa deps/lager/ebin --pa deps/triq/ebin -m paros --treat_as_normal shutdown -a 1000 --ignore_error deadlock

[about half an hour passes, and then]

Error: On step 345, replaying a built-in returned a different result than expected:
  original:
    {event,<0.72.0>,
    {receive_event,
        {message,
            {'DOWN',#Ref<0.0.1.1539>,process,<0.75.0>,shutdown},
            #Ref<0.0.1.57692>,0},
        #Fun<supervisor.8.4433356>,<0.72.0>,infinity,true},
    #Ref<0.0.1.57725>,
    [941,{file,"supervisor.erl"}],
    [{message_received,#Ref<0.0.1.57692>}]}
  new:
    {event,<0.72.0>,
    {receive_event,
        {message,
            {'DOWN',#Ref<0.0.1.1539>,process,<0.75.0>,shutdown},
            #Ref<0.0.1.57883>,0},
        #Fun<supervisor.8.4433356>,<0.72.0>,infinity,true},
    #Ref<0.0.1.57725>,
    [941,{file,"supervisor.erl"}],
    [{message_received,#Ref<0.0.1.57883>}]}

Please notify the developers, as this is a bug of Concuerror.

Done! (Exit status: error)
  Summary: 1 errors, 3981/16270 interleavings explored

**Comment by kostis** [comment]
Thanks @Cloven for your report.  We'll look into it.

**Comment by aronisstav** [comment]
It may take a while for me to figure this one out. In the meantime, I suggest you experiment with using the --instant_delivery option too (long story short, it enforces stronger guarantees on message delivery and should arguably be enabled by default). I tried it with your test and it goes well into > 10.000 interleavings without a problem.

**Comment by Cloven** [comment]
Thanks Stavros, I'll check that option out.  I'm going to move paros ahead
on the master branch soon, so I've created a branch called
'concuerror_issue2' from current master for your use if you need to
replicate the issue.  If there's anything else I can do to help, please let
me know.

**Comment by aronisstav** [comment]
It looks like this particular bug got fixed by one of the recent patches in master! I am closing this issue, but feel free to comment here in case I missed something.

**Comment by aronisstav** [comment]
Nope, just pushed further. I was too optimistic. Testing with 80956fb:
```
$ concuerror --pa ebin --pa deps/goldrush/ebin --pa deps/lager/ebin --pa deps/triq/ebin -m paros --treat_as_normal shutdown -a 1000 --ignore_error deadlock
Concuerror started at 16 Dec 2015 13:06:42
Writing results in concuerror_report.txt

Info: Instrumented io_lib
Info: Instrumented paros
Info: Instrumented paros_sup
Info: Instrumented supervisor
Info: Instrumented gen_server
Info: Instrumented gen
Info: Instrumented proc_lib
Info: Instrumented erlang
Info: Instrumented lists
Info: Instrumented paros_replica
Info: Instrumented paros_kv
Info: Instrumented paros_deps
Info: Instrumented proplists
Info: Instrumented error_logger
Info: Instrumented gen_event
Tip: An abnormal exit signal was sent to a process. This is probably the worst thing that can happen race-wise, as any other side-effecting operation races with the arrival of the signal. If the test produces too many interleavings consider refactoring your code.
Info: Instrumented gen_fsm
Warning: Some abnormal exit reasons were treated as normal (--treat_as_normal).
Info: Instrumented paros_instance
Info: You can see pairs of racing instructions (in the report and --graph) with '--show_races true'
Error: On step 345, replaying a built-in returned a different result than expected:
  original:
    {event,<0.72.0>,
    {receive_event,
        {message,
            {'DOWN',#Ref<0.0.1.1513>,process,<0.75.0>,shutdown},
            #Ref<0.0.1.62598>,0},
        #Fun<supervisor.8.111423185>,<0.72.0>,infinity,true},
    #Ref<0.0.1.62631>,
    [941,{file,"supervisor.erl"}],
    [{message_received,#Ref<0.0.1.62598>}]}
  new:
    {event,<0.72.0>,
    {receive_event,
        {message,
            {'DOWN',#Ref<0.0.1.1513>,process,<0.75.0>,shutdown},
            #Ref<0.0.1.62780>,0},
        #Fun<supervisor.8.111423185>,<0.72.0>,infinity,true},
    #Ref<0.0.1.62631>,
    [941,{file,"supervisor.erl"}],
    [{message_received,#Ref<0.0.1.62780>}]}

Please notify the developers, as this is a bug of Concuerror.

Done! (Exit status: error)
  Summary: 1 errors, 4576/18686 interleavings explored
```

**Comment by Cloven** [comment]
With most recent concuerror, I am still getting these on my other branch (recovery_protocol) as well: 

../Concuerror/concuerror --pa ebin --pa deps/goldrush/ebin --pa deps/lager/ebin --pa deps/triq/ebin -m paros --treat_as_normal shutdown -a 100 --ignore_error deadlock -k --instant_delivery
Concuerror started at 16 Dec 2015 18:13:43
Writing results in concuerror_report.txt

Info: Instrumented io_lib
Info: Instrumented paros
Info: Instrumented paros_sup
Info: Instrumented supervisor
Info: Instrumented gen_server
Info: Instrumented gen
Info: Instrumented proc_lib
Info: Instrumented erlang
Info: Instrumented lists
Info: Instrumented paros_replica
Info: Instrumented paros_kv
Info: Instrumented paros_deps
Info: Instrumented proplists
Info: Instrumented error_logger
Info: Instrumented gen_event
Info: Instrumented gen_fsm
Info: Instrumented paros_instance
Info: You can see pairs of racing instructions (in the report and --graph) with '--show_races true'
Warning: Some errors were ignored ('--ignore_error').
Warning: Continuing after error
Error: On step 362, replaying a built-in returned a different result than expected:
  original:
    {event,<0.128.0>,
    {receive_event,
        {message,
            {'$gen_cast',{commit,{0,{set,x,2},2,[{bruce,1}],{mary,1}}}},
            #Ref<0.0.1.104842>,0},
        #Fun<gen_server.0.77557606>,<0.128.0>,infinity,false},
    #Ref<0.0.1.105001>,
    [382,{file,"gen_server.erl"}],
    [{message_received,#Ref<0.0.1.104842>}]}
  new:
    {event,<0.128.0>,
    {receive_event,
        {message,
            {'$gen_cast',{commit,{0,{set,x,2},2,[{bruce,1}],{mary,1}}}},
            #Ref<0.0.1.104903>,0},
        #Fun<gen_server.0.77557606>,<0.128.0>,infinity,false},
    #Ref<0.0.1.105001>,
    [382,{file,"gen_server.erl"}],
    [{message_received,#Ref<0.0.1.104903>}]}

Please notify the developers, as this is a bug of Concuerror.

Done! (Exit status: error)
  Summary: 1 errors, 2168/2847 interleavings explored

**Comment by Cloven** [comment]
I dunno if this is relevant, but in screwing around with the parameters, and removing the -a flag, I got this:

./Concuerror/concuerror --pa ebin --pa deps/goldrush/ebin --pa deps/lager/ebin --pa deps/triq/ebin -m paros --treat_as_normal shutdown --ignore_error deadlock -k --instant_delivery
Concuerror started at 16 Dec 2015 19:35:04
Writing results in concuerror_report.txt

Info: Instrumented io_lib
Info: Instrumented paros
Info: Instrumented paros_sup
Info: Instrumented supervisor
Info: Instrumented gen_server
Info: Instrumented gen
Info: Instrumented proc_lib
Info: Instrumented erlang
Info: Instrumented lists
Info: Instrumented paros_replica
Info: Instrumented paros_kv
Info: Instrumented paros_deps
Info: Instrumented proplists
Info: Instrumented error_logger
Info: Instrumented gen_event
Info: Instrumented gen_fsm
Info: Instrumented paros_instance
Warning: Concuerror does not fully support erlang:get_stacktrace/0, returning an empty list instead. If you need proper support, notify the developers to add this feature.
Info: Instrumented sys
Tip: A process crashed with reason '{timeout, ...}'. This may happen when a call to a gen_server (or similar) does not receive a reply within some standard timeout. Use the '--after_timeout' option to treat after clauses that exceed some threshold as 'impossible'.
Tip: An abnormal exit signal was sent to a process. This is probably the worst thing that can happen race-wise, as any other side-effecting operation races with the arrival of the signal. If the test produces too many interleavings consider refactoring your code.
Warning: Continuing after error
Error: Concuerror does not support calls to built-in erlang:monotonic_time/1 (found in supervisor.erl line 1390).
  If you cannot avoid its use, please contact the developers.
  Stacktrace:
    [{supervisor,add_restart,1,[{file,"supervisor.erl"},{line,1390}]},
     {supervisor,restart,2,[{file,"supervisor.erl"},{line,777}]},
     {supervisor,handle_info,2,[{file,"supervisor.erl"},{line,614}]}]

Done! (Exit status: error)

note that the concept of time itself has changed in erlang in R18, and that old calls to the time module have been refactored throughout the codebase to erlang:monotonic_time and the like.  So, e.g., supervisor behavior uses that BIF.

**Comment by aronisstav** [comment]
Regarding the previous comment, I just merged some rudimentary support for all the functions that replaced `erlang:now/0`.

**Comment by aronisstav** [comment]
@Cloven: Similar with #75 , this one has been exploring 28687 interleavings (and counting) with no issue. The 'gap' between explored and remaining is growing faster than the other one however, so I'm not sure this will ever finish.

Please take a look at your end and let me know if I can close the issue.

**Comment by Cloven** [comment]
Hi Stavros -- thanks for the apparent fix.  I'll keep exploring.  I would have expected the number of interleavings to be significantly fewer given that code, but that may be a separate issue.
